services:
  - type: web
    name: chatbot
    env: python
    plan: free
    rootDirectory: chatbot        # <-- points to your app folder
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn chat:app
    autoDeploy: true
    runtime: python-3.10.13
